version: '3.8'
 
services:
    db:
        platform: linux/x86_64
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=123456
            - MYSQL_DATABASE=todo_mvc
            - MYSQL_USER=user
        ports:
            - "9906:3306"
    web:
        build: .
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8100:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
            
volumes:
  my-db: 